### PR TITLE
energy device class support

### PR DESCRIPTION
**Pull request by MattBavaria**
for solar heat meters reporting their energy gain in Wh, an appropriate symbol as well as device and state classes are added 
these entities can now be integrated in HA energy dashboard directly

image

### CODE REVIEW

**Review by dm82m — APPROVED** [review]
thanks for contribution

**Comment by dm82m** [comment]
@MattBavaria my heat_quantity sensor is always 0, any idea why?

**Comment by hoppel118** [comment]
> @MattBavaria my heat_quantity sensor is always 0, any idea why?

Did you configure your WMZ (Wärmemengenzähler)? I did this on my Viessmann Vitosolic 200 SD4.

**Comment by dm82m** [comment]
I am using weishaupt gas heating system. Maybe this function is not existing in this combination.

**Comment by hoppel118** [comment]
It is a configurable option in the menu of my Vitosolic 200 SD4. Did you check your Weishaupt heating system menu for on option?

**Comment by MattBavaria** [comment]
Thank you for integrating.
Did not realize, that RESOL VB bus system is used for heating systems providing energy meter function as well.
For me it's a special configuration of the regulator.  A seperate pressure sensor and a flowmeter are used to calculate the solar energy gain.

**Pull request merged**
