### PR TITLE
Adding support for DLX filtered live view

### PR DESCRIPTION
**Pull request by ostat**
Updated to add support for the DLX filtered live view.
This is working if I hard code the filter value. However the config setup for **CONF_FILTER** is not correct. HA does not seem to accept it. it gives an error `ImportError: cannot import name 'CONF_FILTER' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`. Any help working out why would be appreciated.

Also 
* Change the name of the logger, believe it should be **custom_components** not **custom_component**.
* Added support for extracting data from multiple headers if they exists. My DL3 has some sensors, as well as the DeltaSol. The values come on separate headers.

### CODE REVIEW

**Comment by dm82m** [comment]
and please describe that new optional parameter in **readme.md** and **info.md**

**Comment by dm82m** [comment]
ah and the configuration.yaml key for the filter is api_key

**Comment by ostat** [comment]
Oh right, I assumed we could makeup whatever config name we wanted. Thanks for resolving.

**Comment by ostat** [comment]
We don't currently have any wiki pages, but what do you think about  me adding one for how to use the filter?

**Comment by dm82m** [comment]
You can just start adding it here in the embedded wiki. It is enabled and you should be able to create pages.

**Pull request merged**
